fetch('https://jsonplaceholder.typicode.com/todos/1'
).then(response=>response.json())
.then(data=>console.log(data));
fetch('https://jsonplaceholder.typicode.com/todos/2'
).then(response=>response.json())
.then(data=>console.log(data));
fetch('https://jsonplaceholder.typicode.com/todos/4'
).then(response=>response.json())
.then(data=>console.log(data));
fetch('https://jsonplaceholder.typicode.com/todos/6'
).then(response=>response.json())
.then(data=>console.log(data));
fetch('https://jsonplaceholder.typicode.com/todos/8'
).then(response=>response.json())
.then(data=>console.log(data));
fetch('https://jsonplaceholder.typicode.com/todos/12'
).then(response=>response.json())
.then(data=>console.log(data));
fetch('https://jsonplaceholder.typicode.com/todos/65'
).then(response=>response.json())
.then(data=>console.log(data));